_target_: pytorch_lightning.Trainer

gpus: 1
check_val_every_n_epoch: 1
min_epochs: 100
max_epochs: 300
deterministic: True
enable_model_summary: "full"
num_sanity_val_steps: 0
auto_scale_batch_size: True