# https://mlflow.org

mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: ${run_group}
  tracking_uri: null
  tags: null
  save_dir: ${work_dir}/mlruns
  prefix: ""
  artifact_location: null
