_target_: src.datamodules.datamodules.BinDatamodule

defaults:
  - /data_hyperparameters: bin_data_hyperparameters.yaml

batch_size: 30000
data_stats_path: "train_stats.json"
data_path: ${data_dir}/2021-12-03_twh_quaternions_uaixdlamds.hdf5