command:
  - ${env}
  - python3
  - ${program}
  - +experiments/who_is_alyx_paper=training_size.sweep
  - ${args_no_hyphens}
method: grid
name: training_size_sweep
parameters:
  datamodule.dataset_kwargs.limit_train_time:
    values: [1, 2, 5, 10, 15, 20, 25]
  datamodule.dataset_kwargs.train_time_seed:
    values: [ 204, 727, 671,  89, 685 ]


program: run.py
project: Who-is-alyx
entity: 
