# output paths for hydra logs
run:
  dir: runs/${run_group}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: runs/${run_group}/
  subdir: ${now:%Y-%m-%d_%H-%M-%S}/${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
#job:
#  env_set:
#    EXAMPLE_VAR: "example_value"
